server:
  port: 8443 # Mudar a porta padrão para a porta HTTPS
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: keystore.p12 # O nome do arquivo que você gerou
    key-store-password: 1-nanorai # SUBSTITUA pela sua senha
    key-alias: springboot